---
srcFiles:
  - "!sites/*/files/**"
  - "!xmlrpc.php"
  - "!modules/php/*"
projFiles:
  - "README*"
  - "bin/**"
  - "hooks/**"
  - "src/*.make"
  - "vendor/**"
dest:
  docroot: "html"
  devResources: ""
