@api
Feature: Stanford Paragraph Types
  In order to ensure that the Stanford Paragraphs Types installs properly
  As an end user
  I want to verify the display of content.

  @safe
  Scenario: Check for all paragraph types
    Given I am logged in as a user with the "administrator" role
    Then I am on "admin/structure/field-collections/field_p_cards_card/fields"
    And I should see "field_p_card_action_button"
    And I should see "field_p_card_color"
    And I should see "field_p_card_cta"
    And I should see "field_p_card_file"
    And I should see "field_p_card_hide_cta"
    And I should see "field_p_card_image"
    And I should see "field_p_card_pattern"
    And I should see "field_p_card_text"
    And I should see "field_p_card_title"

    Then I am on "admin/structure/field-collections/field_p_cards_card/display/default"
    And I want to validate select field option "fields[field_p_card_action_button][type]" default value is "hidden"
    And I want to validate select field option "fields[field_p_card_color][type]" default value is "hidden"
    And I want to validate select field option "fields[field_p_card_cta][type]" default value is "link_default"
    And I want to validate select field option "fields[field_p_card_file][type]" default value is "file_url_plain"
    And I want to validate select field option "fields[field_p_card_hide_cta][type]" default value is "hidden"
    And I want to validate select field option "fields[field_p_card_image][type]" default value is "image"
    And I want to validate select field option "fields[field_p_card_pattern][type]" default value is "hidden"
    And I want to validate select field option "fields[field_p_card_text][type]" default value is "text_default"
    And I want to validate select field option "fields[field_p_card_title][type]" default value is "text_default"
    And I want to validate select field option "fields[field_p_card_title][parent]" default value is "group_card_title"

    Then I am on "admin/structure/field-collections/field_p_icon_columns/fields"
    And I should see "field_p_icon_color"
    And I should see "field_p_icon_icon"
    And I should see "field_p_icon_image"
    And I should see "field_p_icon_links"
    And I should see "field_p_icon_title"

    Then I am on "admin/structure/field-collections/field_p_icon_columns/display/default"
    And I want to validate select field option "fields[field_p_icon_color][type]" default value is "hidden"
    And I want to validate select field option "fields[field_p_icon_icon][type]" default value is "fontawesome_icon_formatter"
    And I want to validate select field option "fields[field_p_icon_image][type]" default value is "hidden"
    And I want to validate select field option "fields[field_p_icon_links][type]" default value is "link_default"
    And I want to validate select field option "fields[field_p_icon_links][parent]" default value is "group_p_icon_readmore"
    And I want to validate select field option "fields[field_p_icon_title][type]" default value is "text_default"
    And I want to validate select field option "fields[field_p_icon_title][parent]" default value is "group_p_icon_title"

    Then I am on "admin/structure/paragraphs/p_buttons/fields"
    And I should see "field_p_buttons_button"

    Then I am on "admin/structure/paragraphs/p_buttons/display/default"
    And I want to validate select field option "fields[field_p_buttons_button][type]" default value is "link_default"

    Then I am on "admin/structure/paragraphs/p_callout/fields"
    And I should see "field_p_callout_color"
    And I should see "field_p_callout_more_link"
    And I should see "field_p_callout_text"

    Then I am on "admin/structure/paragraphs/p_callout/display/default"
    And I want to validate select field option "fields[field_p_callout_color][type]" default value is "hidden"
    And I want to validate select field option "fields[field_p_callout_more_link][type]" default value is "link_default"
    And I want to validate select field option "fields[field_p_callout_more_link][parent]" default value is "group_callout_span"
    And I want to validate select field option "fields[field_p_callout_text][type]" default value is "text_default"
    And I want to validate select field option "fields[field_p_callout_text][parent]" default value is "group_callout_span"

    Then I am on "admin/structure/paragraphs/p_cards/fields"
    And I should see "field_p_cards_card"

    Then I am on "admin/structure/paragraphs/p_cards/display/default"
    And I want to validate select field option "fields[field_p_cards_card][type]" default value is "field_collection_view"

    Then I am on "admin/structure/paragraphs/p_hero/fields"
    And I should see "field_p_hero_alignment"
    And I should see "field_p_hero_headline"
    And I should see "field_p_hero_image"
    And I should see "field_p_hero_more_link"
    And I should see "field_p_hero_style"
    And I should see "field_p_hero_superhead"
    And I should see "field_p_hero_video"

    Then I am on "admin/structure/paragraphs/p_hero/display/default"
    And I want to validate select field option "fields[field_p_hero_alignment][type]" default value is "hidden"
    And I want to validate select field option "fields[field_p_hero_headline][type]" default value is "text_default"
    And I want to validate select field option "fields[field_p_hero_headline][parent]" default value is "group_headline_h2"
    And I want to validate select field option "fields[field_p_hero_image][type]" default value is "image"
    And I want to validate select field option "fields[field_p_hero_more_link][type]" default value is "link_default"
    And I want to validate select field option "fields[field_p_hero_more_link][parent]" default value is "group_overlay_text"
    And I want to validate select field option "fields[field_p_hero_style][type]" default value is "hidden"
    And I want to validate select field option "fields[field_p_hero_superhead][type]" default value is "text_default"
    And I want to validate select field option "fields[field_p_hero_superhead][parent]" default value is "group_overlay_text"
    And I want to validate select field option "fields[field_p_hero_video][type]" default value is "video_embed_field"

    Then I am on "admin/structure/paragraphs/p_icon/fields"
    And I should see "field_p_icon_columns"

    Then I am on "admin/structure/paragraphs/p_icon/display/default"
    And I want to validate select field option "fields[field_p_icon_columns][type]" default value is "field_collection_view"

    Then I am on "admin/structure/paragraphs/p_menu/fields"
    And I should see "field_p_menu_file_insert"
    And I should see "field_p_menu_header"
    And I should see "field_p_menu_image"
    And I should see "field_p_menu_image_caption"
    And I should see "field_p_menu_image_insert"
    And I should see "field_p_menu_menu"
    And I should see "field_p_menu_wysiwyg"

    Then I am on "admin/structure/paragraphs/p_menu/display/default"
    And I want to validate select field option "fields[field_p_menu_file_insert][type]" default value is "hidden"
    And I want to validate select field option "fields[field_p_menu_header][type]" default value is "text_default"
    And I want to validate select field option "fields[field_p_menu_header][parent]" default value is "group_header_h2"
    And I want to validate select field option "fields[field_p_menu_image][type]" default value is "image"
    And I want to validate select field option "fields[field_p_menu_image][parent]" default value is "group_featured_image"
    And I want to validate select field option "fields[field_p_menu_image_caption][type]" default value is "text_default"
    And I want to validate select field option "fields[field_p_menu_image_caption][parent]" default value is "group_image_caption"
    And I want to validate select field option "fields[field_p_menu_image_insert][type]" default value is "hidden"
    And I want to validate select field option "fields[field_p_menu_menu][type]" default value is "blockreference_default"
    And I want to validate select field option "fields[field_p_menu_menu][parent]" default value is "group_sidebar"
    And I want to validate select field option "fields[field_p_menu_wysiwyg][type]" default value is "text_default"
    And I want to validate select field option "fields[field_p_menu_wysiwyg][parent]" default value is "group_menu_main"

    Then I am on "admin/structure/paragraphs/p_wysiwyg/fields"
    And I should see "field_p_wysiwyg_body"
    And I should see "field_p_wysiwyg_button"
    And I should see "field_p_wysiwyg_image"
    And I should see "field_p_wysiwyg_title"

    Then I am on "admin/structure/paragraphs/p_wysiwyg/display/default"
    And I want to validate select field option "fields[field_p_wysiwyg_body][type]" default value is "text_default"
    And I want to validate select field option "fields[field_p_wysiwyg_body][parent]" default value is "group_left_column"
    And I want to validate select field option "fields[field_p_wysiwyg_button][type]" default value is "link_default"
    And I want to validate select field option "fields[field_p_wysiwyg_button][parent]" default value is "group_right_column"
    And I want to validate select field option "fields[field_p_wysiwyg_image][type]" default value is "image"
    And I want to validate select field option "fields[field_p_wysiwyg_image][parent]" default value is "group_right_column"
    And I want to validate select field option "fields[field_p_wysiwyg_title][type]" default value is "text_default"
    And I want to validate select field option "fields[field_p_wysiwyg_title][parent]" default value is "group_wysiwyg_title"

    Then I am on "admin/structure/paragraphs/p_wysiwyg/display/full"
    And I want to validate select field option "fields[field_p_wysiwyg_body][type]" default value is "text_default"
    And I want to validate select field option "fields[field_p_wysiwyg_body][parent]" default value is "group_p_wysiwyg_body"
    And I want to validate select field option "fields[field_p_wysiwyg_button][type]" default value is "hidden"
    And I want to validate select field option "fields[field_p_wysiwyg_image][type]" default value is "hidden"
    And I want to validate select field option "fields[field_p_wysiwyg_title][type]" default value is "text_default"
    And I want to validate select field option "fields[field_p_wysiwyg_title][parent]" default value is "group_p_wysiwyg_title"
