Feature: Stanford Sites Jumpstart Academic Layouts
  In order to ensure that the module functions
  As an administrator
  I want to check for context and menus

  @api @safe
  Scenario: Check for blocks
    Given I am logged in as a user with the "administrator" role
    And I am on "admin/structure/block"
    Then I should see "Main Menu - Secondary - 3 Depths"
    And I should see "Main Menu - Primary - 1 Depth"
    Then I am on "admin/structure/menu"
    And I should see "Main menu"
    And I should see "About"
    And I should see "Academics"
    And I should see "News and Events"
    And I should see "People"
    
  @api @safe
  Scenario: Check for context rules
    Given I am logged in as a user with the "administrator" role
    And I am on "admin/structure/context"
    Then I should see "9-col-banner-fsb-homepage"
    And I should see "about_location"
    And I should see "academics_graduate"
    And I should see "all_pages_but_homepage_jsa"
    And I should see "course_search"
    And I should see "courses"
    And I should see "events_calendars"
    And I should see "events_node"
    And I should see "events_past"
    And I should see "events_upcoming"
    And I should see "news"
    And I should see "news_pages"
    And I should see "people_administrators"
    And I should see "people_faculty"
    And I should see "people_grad_students"
    And I should see "people_staff"
    And I should see "publications_landing_page"
    And I should see "publications_nodes"
    And I should see "sitewide_jsa"

  @api @safe @javascript
  Scenario: Check for context reactions
    Given I am logged in as a user with the "administrator" role
    And I am on "admin/structure/context/list/9-col-banner-fsb-homepage/edit"
    Then I click on the element with css selector ".context-plugin-block a"
    And I should see "Jumpstart Home Page About Block"
    And I should see "Jumpstart Home Page Academics Block"
    And I should see "Jumpstart Home Page Banner Image"
    And I should see "View: News: 2 Item Recent News List Block"
    And I should see "View: Stanford Events List: 2 Item Upcoming Block - Date Stacked"
    And I should see "Jumpstart Affiliated Programs"
    Then I am on "admin/structure/context/list/about_location/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Jumpstart Location Map Block"
    Then I am on "admin/structure/context/list/academics_graduate/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Jumpstart Our Graduate Students"
    Then I am on "admin/structure/context/list/all_pages_but_homepage_jsa/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Main Menu - Secondary - 3 Depths"
    Then I am on "admin/structure/context/list/course_search/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Exposed form: courses_reference-search_page"
    Then I am on "admin/structure/context/list/courses/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Jumpstart Featured Course"
    And I should see "Exposed form: courses_reference-search_page"
    Then I am on "admin/structure/context/list/events_calendars/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Calendar of Events"
    Then I am on "admin/structure/context/list/events_past/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Exposed form: stanford_events_views-past_events_page"
    And I should see "Calendar of Events"
    Then I am on "admin/structure/context/list/events_upcoming/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Exposed form: stanford_events_views-page"
    And I should see "Calendar of Events"
    Then I am on "admin/structure/context/list/news/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Exposed form: stanford_news-page_1"
    And I should see "Jumpstart Twitter Block"
    Then I am on "admin/structure/context/list/news_pages/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Jumpstart Twitter Block"
    Then I am on "admin/structure/context/list/people_administrators/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Jumpstart Contact Us Postcard"
    Then I am on "admin/structure/context/list/people_faculty/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Jumpstart Why I Teach Block"
    Then I am on "admin/structure/context/list/people_grad_students/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see ""
    Then I am on "admin/structure/context/list/people_staff/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Jumpstart Contact Us Postcard"
    Then I am on "admin/structure/context/list/publications_landing_page/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see ""
    And I should see "Jumpstart Publications Something to Add"
    Then I am on "admin/structure/context/list/publications_nodes/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "View: Publications Common: 4 Item Most Recent Publications Block"
    Then I am on "admin/structure/context/list/sitewide_jsa/edit"
    And I click on the element with css selector ".context-plugin-block a"
    And I should see "Main Menu - Primary - 1 Depth"
    And I should see "Search form"
    And I should see "About"
    And I should see "Academics"
    And I should see "People"
    And I should see "News and Events"
    And I should see "Jumpstart Footer Social Media Connect Block"
    And I should see "Jumpstart Footer Contact Block"