#!/usr/bin/env bash

# Console colors
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'


fin project rm -f
fin project start

echo
echo "In order for Grunt to scaffold the site correctly, you first need to edit Gruntconfig.json, Gruntfile.js and settings.local.php, all located in the src_files dir. "
echo
read -p "Are you sure you want to continue? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo
    echo "Note: you can run ${green_bg}fin grunt-init ${NC}later to set scaffold Drupal site."
    echo
    exit 1
fi
fin grunt-init
echo
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
echo
