Feature: Stanford School of Engineering Menus
  In order to ensure that the SoE menus are configured correctly
  I want to check for the correct menu items

  @live
  Scenario: Verify that we have the correct main navigation items
    Given I am on the homepage
    Then I should see "Admission & Aid" in the "Main Navigation" region
    Then I should see "Students & Academics" in the "Main Navigation" region
    Then I should see "Faculty & Research" in the "Main Navigation" region
    Then I should see "Get Involved" in the "Main Navigation" region
    And I should see "About" in the "Main Navigation" region

  @live
  Scenario: Verify that we have the correct Admission & Aid navigation items
    Given I am on the homepage
    When I click "Admission & Aid"
    Then I should be on "admission-aid"

    When I click "Graduate Admission"
    Then I should be on "admission-aid/graduate-admission"

    When I click "Coterm"
    Then I should be on "admission-aid/coterminal-study-engineering"

    When I click "Financial Aid"
    Then I should be on "admission-aid/financial-aid"

  @live
  Scenario: Verify that we have the correct Students & Academics navigation items
    Given I am on the homepage
    When I click "Students & Academics"
    Then I should be on "students-and-academics"

    When I click "Academics"
    Then I should be on "students-academics/academics"
    When I click "Undergraduate Degree Programs"
    Then I should be on "students-academics/academics/undergraduate-degree-programs"
    When I click "Graduate Degree Programs"
    Then I should be on "students-academics/academics/graduate-degree-programs"
    When I click "Online Learning"
    Then I should be on "students-academics/academics/online-learning"
    When I click "Student Awards"
    Then I should be on "students-academics/academics/frederick-emmons-terman-engineering-scholastic-award"

    When I click "Support and Resources"
    Then I should be on "students-academics/support-and-resources"
    When I click "Undergraduate Resources"
    Then I should be on "students-academics/support-and-resources/undergraduate-resources"
    When I click "Graduate Resources"
    Then I should be on "students-academics/support-and-resources/graduate-resources"
    When I click "Academic Advising"
    Then I should be on "students-academics/support-and-resources/academic-advising"
    When I click "Career Resources"
    Then I should be on "students-academics/support-and-resources/career-resources"
    When I click "Jobs and Internships"
    Then I should be on "students-academics/support-and-resources/jobs-and-internships"
    When I click "International Students"
    Then I should be on "students-academics/support-and-resources/international-students"
    When I click "Student Group Funding"
    Then I should be on "https://ughb.stanford.edu/jobs-opportunities/student-group-funding"
    And I am on "students-academics/support-and-resources"
    When I click "Student Organizations"
    Then I should be on "students-academics/support-and-resources/student-organizations"
    When I click "Terman Engineering Library"
    Then I should be on "students-academics/support-and-resources/terman-engineering-library"

    When I click "Global Engineering Programs"
    Then I should be on "students-academics/global-engineering-programs"
    When I click "Faculty-led programs"
    Then I should be on "students-academics/global-engineering-programs/study-tours"
    When I click "International Internships"
    Then I should be on "students-academics/global-engineering-programs/internships"
    When I click "Chinese UGVR Program"
    Then I should be on "students-academics/programs/global-engineering-programs/chinese-ugvr"
    When I click "Travel Information"
    Then I should be on "students-academics/global-engineering-programs/travel-information"

    When I click "Equity and Inclusion Initiatives"
    Then I should be on "students-academics/equity-and-inclusion-initiatives"
    When I click "About the Equity and Inclusion Initiatives"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/about-equity-and-inclusion-initiatives"
    When I click "STEM K-12 Education Initiatives"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/about-equity-and-inclusion-initiatives/stem-k-12"
    When I click "Funding and Financial Aid"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/funding-and-financial-aid"
    When I click "Undergraduate Financial Aid"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/funding-and-financial-aid/financial-aid"
    When I click "Graduate Funding"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/graduate-programs/graduate-funding"
    When I click "Graduate Fellowships"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/graduate-programs/graduate-fellowships"
    When I click "Undergraduate Programs"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/undergraduate-programs"
    When I click "Summer Engineering Academy"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/undergraduate-programs/summer-engineering"
    When I click "Summer Session Grants"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/undergraduate-programs/summer-session-grants"
    When I click "Additional Calculus for Engineers (ACE)"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/undergraduate-programs/additional-calculus"
    When I click "Prospective Graduate Students"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/prospective-graduate-students"
    When I click "Graduate Pathways to STEM"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/prospective-graduate-students/graduate-pathways"
    When I click "Summer Undergraduate Research Fellowship"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/undergraduate-programs/summer-undergraduate"
    When I click "SERGE: Stanford Exposure to Research and Graduate Education"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/prospective-graduate-students/serge-stanford"
    When I click "Fee Waivers"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/graduate-programs/fee-waivers"
    When I click "Graduate Programs"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/graduate-programs"
    When I click "Graduate Student Community"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/graduate-programs/graduate-student-community"
    When I click "Summer Opportunities in Engineering Research and Leadership (Summer First)"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/graduate-programs/summer-opportunities"
    When I click "NSF Research Exchange Program"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/graduate-programs/nsf-research-exchange-program"
    When I click "Student Societies"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/graduate-programs/student-societies"
    When I click "Engineering Equity Innovation Partnership Micro-Grants"
    Then I should be on "students-academics/equity-and-inclusion-initiatives/engineering-equity-innovation-partnership-micro"

    When I click "Technical Communication Program"
    Then I should be on "students-academics/technical-communication-program"
    When I click "Consulting Request Form"
    Then I should be on "students-academics/technical-communication-program/consulting-request-form"
    When I click "Frequently Asked Questions"
    Then I should be on "students-academics/technical-communication-program/tcp-frequently-asked-questions"

    When I click "The Student Experience"
    Then I should be on "students-academics/student-experience"

  @live
  Scenario: Verify that we have the correct Faculty & Research navigation items
    Given I am on the homepage
    When I click "Faculty & Research"
    Then I should be on "faculty-research"

    When I click "Faculty"
    Then I should be on "people/faculty/grid"
    When I click "Emeritus Faculty"
    Then I should be on "people/emeritus/grid"
    When I click "In Memoriam"
    Then I should be on "people/in-memoriam/grid"

    When I click "Events"
    Then I should be on "events/upcoming-events"

    When I click "Departments"
    Then I should be on "faculty-research/departments"
    When I click "Aeronautics & Astronautics"
    Then I should be on "faculty-research/departments/aeronautics-astronautics"
    When I click "Bioengineering"
    Then I should be on "faculty-research/departments/bioengineering"
    When I click "Chemical Engineering"
    Then I should be on "faculty-research/departments/chemical-engineering"
    When I click "Civil & Environmental Engineering"
    Then I should be on "faculty-research/departments/civil-environmental-engineering"
    When I click "Computer Science"
    Then I should be on "faculty-research/departments/computer-science"
    When I click "Electrical Engineering"
    Then I should be on "faculty-research/departments/electrical-engineering"
    When I click "Management Science & Engineering"
    Then I should be on "faculty-research/departments/management-science-engineering"
    When I click "Materials Science & Engineering"
    Then I should be on "faculty-research/departments/materials-science-engineering"
    When I click "Mechanical Engineering"
    Then I should be on "faculty-research/departments/mechanical-engineering"

    When I click "Institutes, Labs and Centers"
    Then I should be on "faculty-research/institutes-labs-and-centers"

    When I click "Faculty Awards"
    Then I should be on "faculty-research/faculty-awards/faculty-awards"
    When I click "2015-2016"
    Then I should be on "faculty-research/faculty-awards/faculty-awards-2015-2016"
    When I click "2014-2015"
    Then I should be on "faculty-research/faculty-awards/faculty-awards-2014-2015"
    When I click "2012-2013"
    Then I should be on "faculty-research/faculty-awards/faculty-awards-2012-2013"
    When I click "2011-2012"
    Then I should be on "faculty-research/faculty-awards/faculty-awards-2011-2012"
    When I click "2010-2011"
    Then I should be on "faculty-research/faculty-awards/faculty-awards-2010-2011"
    When I click "2009-2010"
    Then I should be on "faculty-research/faculty-awards/faculty-awards-2009-2010"
    When I click "2008-2009"
    Then I should be on "faculty-research/faculty-awards/faculty-awards-2008-2009"
    When I click "2007-2008"
    Then I should be on "faculty-research/faculty-awards/faculty-awards-2007-2008"
    When I click "2006-2007"
    Then I should be on "faculty-research/faculty-awards/faculty-awards-2006-2007"
    When I click "2005-2006"
    Then I should be on "faculty-research/faculty-awards/faculty-awards-2005-2006"

  @live
  Scenario: Verify that we have the correct Get Involved navigation items
    Given I am on the homepage
    When I click "Get Involved"
    Then I should be on "get-involved"

    When I click "Support Engineering"
    Then I should be on "get-involved/give"
    When I click "Funding Initiatives"
    Then I should be on "get-involved/give/stanford-engineering-funding-initiatives"
    When I click "Aeronautics and Astronautics Undergraduate Major"
    Then I should be on "get-involved/give/aeronautics-and-astronautics-undergraduate-major"
    When I click "Coterm Opportunity Fellowship Program"
    Then I should be on "get-involved/give/coterm-opportunity-fellowship-program"
    When I click "Endowed Department Chairs"
    Then I should be on "get-involved/give/endowed-department-chairs"
    When I click "Endowed Faculty Scholars"
    Then I should be on "get-involved/give/endowed-faculty-scholars"
    When I click "Endowed Graduate Fellowships"
    Then I should be on "get-involved/give/endowed-graduate-fellowships"
    When I click "Endowed Professorships"
    Then I should be on "get-involved/give/endowed-professorships"
    When I click "Hasso Plattner Institute of Design"
    Then I should be on "get-involved/give/hasso-plattner-institute-design"

    When I click "Planned Giving"
    Then I should be on "get-involved/give/planned-giving"

    When I click "Annual Giving"
    Then I should be on "get-involved/give/annual-giving"
    When I click "Why Give"
    Then I should be on "get-involved/support-engineering/annual-giving/5-reasons-support-stanford"
    When I click "Leadership Annual Giving"
    Then I should be on "get-involved/give/annual-giving/leadership-annual-giving"

    When I click "How to Make Your Gift"
    Then I should be on "get-involved/give/how-make-your-gift"

    When I click "Development Contacts"
    Then I should be on "get-involved/development-contacts"

    When I click "Industry Collaborations"
    Then I should be on "get-involved/industry-collaborations"
    When I click "Gift Support"
    Then I should be on "get-involved/industry-collaborations/gift-support"
    When I click "Affiliate Programs"
    Then I should be on "get-involved/industry-collaborations/affiliate-programs"
    When I click "Sponsored Research"
    Then I should be on "get-involved/industry-collaborations/sponsored-research"
    When I click "Recruiting"
    Then I should be on "get-involved/industry-collaborations/recruit-students-and-alumni"
    When I click "Executive Education"
    Then I should be on "get-involved/industry-collaborations/executive-education"
    When I click "Technology Transfer/Technology Licensing"
    Then I should be on "get-involved/industry-collaborations/technology-transfertechnology-licensing"

    When I click "Alumni"
    Then I should be on "get-involved/alumni"
    When I click "Career Resources"
    Then I should be on "get-involved/alumni/career-resources"
    When I click "Alumni Events"
    Then I should be on "get-involved/alumni/alumni-events"
    When I click "Volunteer"
    Then I should be on "get-involved/alumni/volunteer"

  @live
  Scenario: Verify that we have the correct About navigation items
    Given I am on the homepage
    When I click "About"
    Then I should be on "about"
    When I click "Dean"
    Then I should be on "about/dean"
    When I click "Dean’s Office"
    Then I should be on "about/dean-s-office"
    When I click "Heroes"
    Then I should be on "about/heroes"
    When I click "School News"
    Then I should be on "news/school-news"
    When I click "History"
    Then I should be on "about/history"
    When I click "Visit"
    Then I should be on "about/visit"
    When I click "SoE-Future"
    Then I should be on "about/soe-future"
